### ISSUE TITLE
Failure on prometheus metrics start

### ISSUE THREAD

**Issue by knabben** [kubernetes-sigs/windows-service-proxy#34]
Prometheus register is failing with a nil pointer. Need to check the wrong variable and fix.

```
I0217 12:50:51.127820    1452 proxier.go:423] "Record sync param" minSyncPeriod="0s" syncPeriod="15s" burstSyncs=2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0xe9ed4c]

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).Register(0xc00015e550, {0x23b89e0?, 0xc0001e3830?})
	/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:294 +0x26c
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0001590a0?, {0xc00050a000?, 0x1, 0x23d19e8?})
	/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:405 +0x53
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:178
sigs.k8s.io/windows-service-proxy/backend/kernelspace/metrics.RegisterMetrics.func1()
	/src/backend/kernelspace/metrics/metrics.go:30 +0x70
sync.(*Once).doSlow(0x0?, 0x15?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
sigs.k8s.io/windows-service-proxy/backend/kernelspace/metrics.RegisterMetrics()
	/src/backend/kernelspace/metrics/metrics.go:29 +0x31
sigs.k8s.io/windows-service-proxy/backend/kernelspace.(*Backend).Setup(0x0?)
	/src/backend/kernelspace/register.go:127 +0x93c
sigs.k8s.io/kpng/client/localsink/filterreset.(*Sink).Setup(0x0?)
	/go/pkg/mod/sigs.k8s.io/kpng/client@v0.0.0-20230108201327-8afcc15982a4/localsink/filterreset/filterreset.go:47 +0x22
sigs.k8s.io/kpng/server/jobs/store2localdiff.(*Job).Run(0xc000431140, {0x23c8f70, 0xc0003bca40})
	/go/pkg/mod/sigs.k8s.io/kpng/server@v0.0.0-20230108201327-8afcc15982a4/jobs/store2localdiff/store2localdiff.go:56 +0xee
sigs.k8s.io/kpng/cmd/kpng/builder.ToLocalCmd.func2({0x23c9980?, 0xc0001f6000})
	/go/pkg/mod/sigs.k8s.io/kpng/cmd@v0.0.0-20230108201327-8afcc15982a4/kpng/builder/command_builder.go:118 +0xaa
sigs.k8s.io/kpng/cmd/kpng/builder.LocalCmds.func1(0xc0000baf00?, {0x2105946?, 0x4?, 0x4?})
	/go/pkg/mod/sigs.k8s.io/kpng/cmd@v0.0.0-20230108201327-8afcc15982a4/kpng/builder/command_builder.go:134 +0x35
github.com/spf13/cobra.(*Command).execute(0xc0000baf00, {0xc0003bce00, 0x4, 0x4})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ba600)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
```

**Comment by samyakjain10** [comment]
Was wondering if this issue is up for grabs?

**Comment by knabben** [comment]
Yes the task still valid, go ahead.

/assign @samyakjain10
